version: 0.2

phases:
  install:
    commands:
      - sudo apt update
      - sudo apt install python3-pip -y
      - pip3 install flask
      - mkdir -p /home/ubuntu/app
  pre_build:
    commands:
      - echo "No tests to run"
  build:
    commands:
      - echo "No build step required for simple Flask app"
  post_build:
    commands:
      - echo "Build completed"
