version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build: No actions"
  build:
    commands:
      - echo "Zipping application for deployment"
      - zip -r flask-app.zip .
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - flask-app.zip
